sudo: required
services:
  - docker

before_install:
  - docker build -t ysahakyan1998/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ysahakyan1998/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "frontend-1"
  env: "Frontend-1-env"
  bucket_name: "elasticbeanstalk-eu-central-1-597281801493"
  bucket_path: "frontend-1"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"